build:
  stage: build
  script:
    - for i in $(seq 1 64); do mknod /dev/loop$i -m0660 b 7 $i; done
    - LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE="en_US.UTF-8" LC_NUMERIC="en_US.UTF-8" LC_TIME="en_US.UTF-8" LC_COLLATE="en_US.UTF-8" LC_MONETARY="en_US.UTF-8" LC_MESSAGES="en_US.UTF-8" LC_PAPER="en_US.UTF-8" LC_NAME="en_US.UTF-8" LC_ADDRESS="en_US.UTF-8" LC_TELEPHONE="en_US.UTF-8" LC_MEASUREMENT="en_US.UTF-8" LC_IDENTIFICATION="en_US.UTF-8" LC_ALL= bash create-image.sh
  artifacts:
    paths:
      - wyper.iso
      - wyper.img

variables:
  GIT_SUBMODULE_STRATEGY: recursive

